stages:
  - deploy

pages:
  stage: deploy
  image: python:3.8.3
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip3 install sphinx sphinx_book_theme sphinx-autodoc-typehints sphinxcontrib-napoleon numpy samna
  script:
    - cd doc && make html
  after_script:
    - mv doc/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "samna-dynapse1"'