#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  6 17:05:47 2020

Ctxctl parameters

@author: nrisi
"""

NUM_NEURONS_PER_CORE = 256
NUM_CORES_PER_CHIP = 4
NUM_CHIPS_PER_BOARD = 4
NUM_NEURONS_PER_CHIP = NUM_NEURONS_PER_CORE*NUM_CORES_PER_CHIP
NUM_NEURONS_PER_BOARD = NUM_NEURONS_PER_CHIP*NUM_CHIPS_PER_BOARD
NUM_CAMS_PER_NEURON = 64

ADDR_NUM_BITS = 15
ISI_NUM_BITS = 16