#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  6 17:05:47 2020

Ctxctl parameters

@author: nrisi
"""
NUM_NEURONS_PER_ROW = 16
NUM_NEURONS_PER_COL = 16
NUM_CORES_PER_CHIP = 4
NUM_CHIPS_PER_BOARD = 4
NUM_NEURONS_PER_CORE = NUM_NEURONS_PER_ROW*NUM_NEURONS_PER_COL
NUM_NEURONS_PER_CHIP = NUM_NEURONS_PER_CORE*NUM_CORES_PER_CHIP
NUM_NEURONS_PER_BOARD = NUM_NEURONS_PER_CHIP*NUM_CHIPS_PER_BOARD
NUM_CAMS_PER_NEURON = 64

ADDR_NUM_BITS = 15
ISI_NUM_BITS = 16

LINEAR_BIAS_RANGE = 2400000000

SOURCE_TRIGGER_NRN_ID = 1023
TARGET_TRIGGER_NRN_ID = 4095

NP_SEED = 1993 