# global NEURONS_PER_CORE, CORES_PER_CHIP, NEURONS_PER_CHIP, MAX_NUM_CAMS, NUM_CHIPS

NEURONS_PER_CORE = 256
CORES_PER_CHIP = 4
NEURONS_PER_CHIP = NEURONS_PER_CORE * CORES_PER_CHIP
MAX_NUM_CAMS = 64
NUM_CHIPS = 4